version: "3"
services:
  app:
    build: .
    command: node build/main.js
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - RCON_IP=${RCON_IP}
      - RCON_PORT=${25575}
      - RCON_PASS=${RCON_PASS}
