version: "3"
services:
  fembot:
    container_name: fembot
    restart: unless-stopped
    image: fembot:latest
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - RCON_IP=${RCON_IP}
      - RCON_PORT=${RCON_PORT}
      - RCON_PASS=${RCON_PASS}
